name: Tests
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    name: Test of Compiler
    steps:
    - name: Clone GIT repo
      uses: actions/checkout@v4
    - uses: korandoru/setup-zig@v1
      with:
        zig-version: 0.13.0
    - uses: actions/setup-python@v3
      with:
        python-version: 3.12.3

    - name: Install FASM
      run: |
        sudo apt update
        sudo apt install -y fasm

    - name: All Test
      run: python3 test.py
